name: flutter_architecture
description: 试着自己写个flutter | 借着有个已成的项目

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  http: ^0.11.3
  dio: 0.1.3
  cached_network_image: ^0.4.1
  json_annotation: ^0.2.5
  banner: ^0.0.5
  flutter_advanced_networkimage: any


dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^0.8.9
  json_serializable: ^0.5.4

  path: ^1.5.1
  test: ^0.12.37

dependency_overrides:
   analyzer: any
   kernel: any
   front_end: any

flutter:
  uses-material-design: true
  assets:
    - assets/error.jpg


environment:
  sdk: '>=2.0.0-dev.54 <2.0.0'

